#!/bin/bash
set -euo pipefail

CONFIG_FILE=${CONCIERGE_CONFIG_FILE:-/etc/concierge/concierge.env}
if [ -f /Library/Application\ Support/Concierge.AI/concierge.env ]; then
    CONFIG_FILE=/Library/Application\ Support/Concierge.AI/concierge.env
fi
set -a
# This file is generated by the root-owned installer and writable only by root.
# shellcheck disable=SC1090
. "$CONFIG_FILE"
set +a
cd /opt/concierge/current
exec /opt/concierge/current/.venv/bin/python -m uvicorn app.main:app \
    --host 127.0.0.1 --port "${CONCIERGE_INTERNAL_PORT:-8080}" --workers 1 --no-proxy-headers
