import sqlite3

import pytest

from app import metrics
from app.database import _CompatRow, _qmark_to_named, _split_statements, _translate_sql, connect_database, table_columns, table_exists


def test_qmark_translation_preserves_question_marks_inside_sql_strings():
    sql, params = _qmark_to_named("SELECT '?' AS literal, value FROM sample WHERE id=? AND label=?", (7, "front desk"))
    assert sql == "SELECT '?' AS literal, value FROM sample WHERE id=:p0 AND label=:p1"
    assert params == {"p0": 7, "p1": "front desk"}


def test_qmark_translation_rejects_mismatched_parameters():
    with pytest.raises(ValueError, match="parameter count"):
        _qmark_to_named("SELECT * FROM sample WHERE id=?", ())


def test_legacy_sqlite_constructs_translate_to_parameterized_postgresql():
    query, params = _translate_sql(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", ("departments",)
    )
    assert "information_schema.tables" in query
    assert "table_schema=current_schema()" in query
    assert params == {"p0": "departments"}

    ddl, _ = _translate_sql("CREATE TABLE sample (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT)")
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in ddl

    insert, params = _translate_sql("INSERT OR IGNORE INTO sample(label) VALUES (?)", ("x",))
    assert insert.endswith("ON CONFLICT DO NOTHING")
    assert params == {"p0": "x"}


def test_pragma_table_info_translation_and_compatibility_rows():
    sql, params = _translate_sql("PRAGMA table_info(sample)")
    assert "information_schema.columns" in sql
    assert params == {"table_name": "sample"}
    row = _CompatRow(("cid", "name"), (0, "property_id"))
    assert row[1] == "property_id"
    assert row["name"] == "property_id"
    assert dict(row) == {"cid": 0, "name": "property_id"}


def test_script_splitter_respects_semicolons_inside_literals():
    statements = _split_statements("INSERT INTO sample(value) VALUES ('a;b'); SELECT 1;")
    assert statements == ["INSERT INTO sample(value) VALUES ('a;b')", "SELECT 1"]


def test_runtime_postgres_configuration_rejects_sqlite_database_urls(tmp_path, monkeypatch):
    monkeypatch.delenv("CONCIERGE_TESTING", raising=False)
    from app.config import Settings, validate_production_settings

    values = Settings(
        app_environment="production",
        db_path=tmp_path / "concierge.db",
        state_directory=tmp_path,
        property_id="hotel-a",
        antlabs_mode="browser_handoff",
        antlabs_auth_url="https://gateway.example/login/main.ant?c=proc",
        admin_bootstrap_password="A-Strong-Production-Pass-123!",
        credential_encryption_secret="x" * 48,
        admin_cookie_secure=True,
        allow_body_property_selection=False,
        allow_demo_settings=False,
        canonical_hosts=("concierge.example.test",),
        admin_allowed_cidrs=("198.51.100.14/32",),
        public_base_url="https://concierge.example.test",
        forwarded_allow_ips="172.29.0.2",
        database_url="sqlite:///unsafe.db",
        redis_url="redis://redis:6379/0",
        metrics_token="m" * 40,
    )
    with pytest.raises(RuntimeError, match="DATABASE_URL must use PostgreSQL when a server database is configured"):
        validate_production_settings(values, check_filesystem=False)


def test_sqlite_execution_errors_are_counted_for_loadtest_metrics(tmp_path):
    before = metrics.REGISTRY.get_sample_value(
        "concierge_database_errors_total", {"operation": "sqlite_query"}
    ) or 0
    with connect_database(tmp_path / "database-errors.db") as db:
        with pytest.raises(sqlite3.OperationalError):
            db.execute("SELEC invalid syntax")
    after = metrics.REGISTRY.get_sample_value(
        "concierge_database_errors_total", {"operation": "sqlite_query"}
    ) or 0
    assert after == before + 1


def test_schema_inspection_helpers_detect_sqlite_tables_and_columns(tmp_path):
    with connect_database(tmp_path / "schema-inspection.db") as db:
        db.execute("CREATE TABLE schema_fixture (fixture_id TEXT PRIMARY KEY, value TEXT)")
        assert table_exists(db, "schema_fixture")
        assert not table_exists(db, "missing_fixture")
        assert table_columns(db, "schema_fixture") == {"fixture_id", "value"}
        with pytest.raises(ValueError, match="table name"):
            table_exists(db, "schema_fixture; DROP TABLE sessions")
