import pytest

from app.database import _CompatRow, _qmark_to_named, _split_statements, _translate_sql


def test_qmark_translation_preserves_question_marks_inside_sql_strings():
    sql, params = _qmark_to_named("SELECT '?' AS literal, value FROM sample WHERE id=? AND label=?", (7, "front desk"))
    assert sql == "SELECT '?' AS literal, value FROM sample WHERE id=:p0 AND label=:p1"
    assert params == {"p0": 7, "p1": "front desk"}


def test_qmark_translation_rejects_mismatched_parameters():
    with pytest.raises(ValueError, match="parameter count"):
        _qmark_to_named("SELECT * FROM sample WHERE id=?", ())


def test_legacy_sqlite_constructs_translate_to_parameterized_postgresql():
    query, params = _translate_sql(
        "SELECT 1 FROM sqlite_master WHERE type='table' AND name=?", ("departments",)
    )
    assert "information_schema.tables" in query
    assert "table_schema=current_schema()" in query
    assert params == {"p0": "departments"}

    ddl, _ = _translate_sql("CREATE TABLE sample (id INTEGER PRIMARY KEY AUTOINCREMENT, label TEXT)")
    assert "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY" in ddl

    insert, params = _translate_sql("INSERT OR IGNORE INTO sample(label) VALUES (?)", ("x",))
    assert insert.endswith("ON CONFLICT DO NOTHING")
    assert params == {"p0": "x"}


def test_pragma_table_info_translation_and_compatibility_rows():
    sql, params = _translate_sql("PRAGMA table_info(sample)")
    assert "information_schema.columns" in sql
    assert params == {"table_name": "sample"}
    row = _CompatRow(("cid", "name"), (0, "property_id"))
    assert row[1] == "property_id"
    assert row["name"] == "property_id"
    assert dict(row) == {"cid": 0, "name": "property_id"}


def test_script_splitter_respects_semicolons_inside_literals():
    statements = _split_statements("INSERT INTO sample(value) VALUES ('a;b'); SELECT 1;")
    assert statements == ["INSERT INTO sample(value) VALUES ('a;b')", "SELECT 1"]


def test_runtime_postgres_configuration_rejects_sqlite_database_urls():
    from app.config import Settings, validate_production_settings

    values = Settings(
        app_environment="production",
        property_id="hotel-a",
        antlabs_mode="browser_handoff",
        antlabs_auth_url="https://gateway.example/auth",
        admin_bootstrap_password="A-Strong-Production-Pass-123!",
        credential_encryption_secret="x" * 48,
        admin_cookie_secure=True,
        allow_body_property_selection=False,
        allow_demo_settings=True,
        database_url="sqlite:///unsafe.db",
        redis_url="redis://redis:6379/0",
        metrics_token="m" * 40,
    )
    with pytest.raises(RuntimeError, match="DATABASE_URL must use PostgreSQL"):
        validate_production_settings(values, check_filesystem=False)
